# Generated by Django 4.2.4 on 2023-08-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Breaking', 'Breaking'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Business', 'Business'), ('Health', 'Health')], max_length=50),
        ),
    ]
