# Generated by Django 4.2.4 on 2023-08-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0003_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Breaking', 'Breaking'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Business', 'Business'), ('Health', 'Health')], max_length=100)),
                ('tilte', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
    ]
