# Generated by Django 4.2.4 on 2023-08-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tilte',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
